apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: track-head
  namespace: argocd
spec:
  destination:
    namespace: track-head
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: argocd-example-apps/guestbook
    repoURL: "https://github.com/vagner.aragao/repo.git"
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true

    
