apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: replace-resources
  namespace: argocd
spec:
  destination:
    namespace: replace-resources
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: argocd-example-apps/sync-options/replace
    repoURL: "https://github.com/vagneraragao/repo.git"
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true

      

    
