apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: selective-sync
  namespace: argocd
spec:
  destination:
    namespace: selective-sync
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: argocd-example-apps/sync-options/selective-sync
    repoURL: "https://github.com/vagneraragao/repo.git"
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true

    
