apiVersion: v1
kind: Secret
metadata:
  name: private-repo-https
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/vagneraragao/argocd-example-apps.git
  password: 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
  username: 
