apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: kustomize-app
  namespace: argocd
spec: 
  destination:
    namespace: kustomize-app
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: argocd-example-apps/kustomize-guestbook
    repoURL: "https://github.com/vagneraragao/repo.git"
    targetRevision: master
    kustomize:
      namePrefix: staging-
      commonLabels:
        app: demo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    
