apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: guestbook-dev-project
  namespace: argocd
spec: 
  destination: 
    namespace: ns-1
    server: "https://kubernetes.default.svc"
  project: dev-project
  source: 
    path: argocd-example-apps/guestbook
    repoURL: "https://github.com/vagneraragao/repo.git"
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
